language: node_js
node_js:
  - "0.8"
  - "0.10"

notifications:
  email:
    recipients:
      - martinmicunda@hotmail.com
    on_success: never
    on_failure: always

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g grunt-cli@0.1.x karma@0.8.x
  - npm install --quiet
  - node server/app/server.js &
  - sleep 3 # give server some time to start

script: grunt test
